daemon off;
master_process off;
error_log logs/error.log info;
pid logs/nginx.pid;

worker_processes 1;

events {
    worker_connections 1024;
}

http {
    access_log logs/access.log combined;
    client_body_temp_path client_body_temp;

    upstream ub_echo {
        server 127.0.0.1:18081;
    }

    server {
        listen 127.0.0.1:18080;

        location /view {
            unbuffered_body view;
            proxy_request_buffering off;
            proxy_pass http://ub_echo;
            add_header X-Body-Sha1 $unbuffered_body_sha1 always;
            add_header X-Body-Size $unbuffered_body_size always;
            add_header X-Body-State $unbuffered_body_state always;
        }

        location /consume_access {
            unbuffered_body consume_access;
            proxy_request_buffering off;
            proxy_pass http://ub_echo;
            add_header X-Body-Sha1 $unbuffered_body_sha1 always;
            add_header X-Body-Size $unbuffered_body_size always;
            add_header X-Body-State $unbuffered_body_state always;
        }

        location /consume_content {
            unbuffered_body consume_content;
        }
    }
}
